vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set mouse=r")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set nobackup")
vim.cmd("set nowrap")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("set showcmd")
vim.cmd("set showmode")
vim.cmd("set noswapfile")
vim.cmd("filetype on")
vim.cmd("filetype plugin on")
vim.cmd("filetype indent on")
vim.cmd("syntax on")
vim.g.mapleader = " "
